version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www 
    depends_on:
      - app

  app:
    build:
      context: .
    image: php:8.3-fpm
    container_name: laravel-app
    volumes:
      - .:/var/www
    expose:
      - "9000"
