version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.2-fpm  
    container_name: todo-app
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel
    expose:
      - "9000"  # Ensure this matches the Nginx config

  nginx:
    image: nginx:alpine
    container_name: nginx-server
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf # Marked read-only for safety
      - .:/var/www
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
